### ISSUE TITLE
ch04 他のデータベースの紹介

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#10]
QMとかSBDDにつながるようなデータベースの説明は必要か？

**Comment by inoue0426** [comment]
http://mona.fiehnlab.ucdavis.edu/
MS Spectrumの包括的なDBをUCDavisが提供しています。
スペクトル、構造、クラス、SMILESなど一通りメタ情報が載っています。
裏側ではHMDB、MassBankなどのデータを含んでいます。
参考までに。

**Comment by kzfm** [comment]
紹介ありがとうございます。
MSのデータベースでなにかケモインフォ的な使われ方をしているんでしょうか？
代謝物解析や予測など？

**Comment by inoue0426** [comment]
MS/MSのスペクトルから化合物構造の推定を行うのですが、推定を行うに当たりライブラリサーチ（ライブラリに存在するスペクトルと測定されたスペクトルの比較を行うことで構造のあたりを付けていきます。このとき、スペクトルを機械学習の入力として用い、出力として化合物を返す、というような形で用いられています。また、スペクトルの予測をDeep Learningを用いて行う手法等もあります。https://pubs.acs.org/doi/abs/10.1021/acs.analchem.7b02566?src=recsys&journalCode=ancham

**Comment by kzfm** [comment]
ありがとうございます。読んでみます。

**Comment by kzfm** [comment]
sure ChEMBL
