### ISSUE TITLE
ch09 Free-Wilson 未完了

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#14]
データ探して書く

**Comment by iwatobipen** [comment]
https://github.com/PatWalters/Free-Wilson/tree/master/data
のデータいいと思いますがどうでしょ？

**Comment by kzfm** [comment]
じゃぁ本では手でやって、そのあとGithubへリンクを張りますかね

**Comment by kzfm** [comment]
色々考えてみたけど、R分解がめんどくさいので実装ごと取ってこないといけないっぽいので悩んでいる。

**Comment by iwatobipen** [comment]
別のデータセットあるので後日シェアしますー

**Comment by kzfm** [comment]
Free-Wilson Analysisできても別に嬉しくないのとRDKitでやるのは面倒なので章ごと削除した
