### ISSUE TITLE
ch02 RDKit日本語サイトのこと

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#17]
> 最近では日本語での解説サイトも増えてきており初学者の導入のハードルも低くなってきています。

インストレーションの章で説明すること？

**Comment by kzfm** [comment]
「はじめに」にRDkitとは？というサブチャプター足して、そこで熱く語って貰えばいいのではないでしょうか？

**Comment by iwatobipen** [comment]
熱く語ったでござる
