### ISSUE TITLE
ライセンス

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#18]
CC BY-NC-SAでよいと思うけど？
https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ja

**Comment by iwatobipen** [comment]
やってみたんですがリポジトリの表示が変わらない、、、

**Comment by kzfm** [comment]
webのほうのcreate file からコピペするとか。ま、そのうちパースされるでしょう。チケット閉じます
