### ISSUE TITLE
ヘテロシャッフリングの例が欲しい

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#23]
キナーゼ阻害剤を例にしてシャッフリングする例を追加するといいような気がする

**Comment by iwatobipen** [comment]
前にRDKITでやったのでちょっと漁ってみます。

**Comment by kzfm** [comment]
よろしくおねがいします。

**Comment by iwatobipen** [comment]
ch13に追加してみた。

**Comment by kzfm** [comment]
どこかの章にはいりませんか？
それからヘテロシャッフリングがなぜ必要なのか？具体的なメドケム的な狙いを説明したほうが良いのでは？

**Comment by kzfm** [comment]
5章に入れればいいかな？

論文としてはこのあたりか

- https://pubs.acs.org/doi/10.1021/jm3001289
- https://pubs.acs.org/doi/10.1021/acs.jcim.8b00563

**Comment by iwatobipen** [comment]
対応します

**Comment by kzfm** [comment]
エクスキューズ的な前置きをいれたり、断定を避けるような言い回しは読み手に混乱を招くので避けたほうが良いです。

それからセンテンスあたりの行数が多いので適当なところで区切ってみてください。

一行目はアプローチが二回出てきてます。

ケミスト以外で分かる人いないでしょう。

> 炭素原子をを窒素源信に、チオフェンの硫黄原子を酸素原子に等、芳香族原子を他の芳香族原子に変えつつ新しい分子を生み出す手法

これをエクスキューズする理由が不明
> このMorph自身はコードが公開されておらずすぐに使うことはできません。 ちょっと遅いですが

入門として実行するので不要な文
>  興味のある方は使ってみてください。

そもそもimport で呼ばないでそのままjupyterにコードとして埋め込めばいいのでは？

**Comment by iwatobipen** [comment]
ご指摘ありがとうございます。
上記対応します。

**Comment by kzfm** [comment]
想定読者が内容を理解するのにその情報が必要かどうかを考えてみてください。ヘテロシャッフリングのコードを理解するのにMorphを知っておく必要があるのであれば本文にいれるべきだし、別になくてもいいのだったらそれは親切心による薀蓄ぶっこみなので、NOTEとか余談でおまけ記事にしておけばよいです。

**Comment by iwatobipen** [comment]
コメントありがとうございます。上記の件対応します。
