### ISSUE TITLE
[pdf]気になる点についていくつか

### ISSUE THREAD

**Issue by ghost** [Mishima-syk/py4chemoinformatics#30]
・「RDKitで構造情報を取り扱う」の最初に本章のJupyter notebookへのリンクがあり、
とても便利と感じました。他の章でも、同様のリンクがあれば更に便利だと思いました。
・各セルの出力内容の記載がある場合とない場合があり類推して読むことがありました。

以下は個人的要望ですので参考程度でかまいません。
・個人的に、この入門書を読んだ後に読み進むべき文献や勉強方法があると感激します。
・実際の業務での流れの一例(解説した章のまとめになるもの？)があると感激します。
ケモインフォマティシャンが周りにいない人(自分ですが)は、実際に行われた流れ(に近いもの)があれば、
とても勉強になりますし、こういう話は集会に参加することでしか得られない情報となりがちで貴重に思います。

**Comment by kzfm** [comment]
コメントありがとうございます。別途イシューとして再登録しました。また、扱うデータももう少し触って面白そうな具体的な例を探して順次置き換えていきます。

社内のだと色々あるんだけど出せないｗ
