### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by iwatobipen** [Mishima-syk/py4chemoinformatics#33]
It is useful for translate the document from Japanese to English for some people....
This is not issue, just memo.

**Comment by joofio** [comment]
Hello. Forked the repo and aiming for a english translation. Help welcomed! 😄

**Comment by iwatobipen** [comment]
Thank you for your help. I will contact you when I start the english translation!!
Can you read Japanese?

**Comment by iwatobipen** [comment]
Forked the repo, renamed made 'en' branch.
https://github.com/iwatobipen/py4chemoinformatics_en/tree/en

**Comment by joofio** [comment]
I have my contributions on my fork. I cant read japanese but google translate and good sense can go a long way 😃

**Comment by kzfm** [comment]
@joofio has already started translation to English in his repo, so I guess it's better for us forking his repo and PR to his repo doesn't it?

**Comment by iwatobipen** [comment]
Ah! It sounds nice. I will fork @joofio repo and work. @joofio thank you for your contribution!
