### ISSUE TITLE
第４章の公開データベースの追加候補

### ISSUE THREAD

**Issue by yamasakih** [Mishima-syk/py4chemoinformatics#36]
以下の二つを追加するのはいかがでしょうか？

- ZINC: http://zinc.docking.org/ 購入可能な化合物の大規模データベース たまに論文にも使われています
- DrugBank: https://www.drugbank.ca/ 最近ライセンスがCreative Common’s Attribution-NonCommercial 4.0 International Licenseになったので企業の方はちょっと使いにくいですが

**Comment by yamasakih** [comment]
あ、しまった #10 に追加した方が良かったかもしれませんね。すいません。

**Comment by kzfm** [comment]
zincはちょっと考えてはいたんですけど、バーチャルスクリーニング用のセットとしてはいいですね。追加しておきます。

Drugbankは眺めるだけでケモインフォに使ったことないですけど、なんか利用例ってあるんでしょうか？

**Comment by yamasakih** [comment]
Drugbankはこれぞ！とすぐに言える論文は私の中にないのですが、de Novo でより薬らしい化合物を作りました、みたいな話をする時にDrugbankのデータセットと比較したりその中の化合物 (つまり薬) を再現できましたみたいな論文を見たりしますね。

他にも検索したらちょこちょこでるようです (drug bank と検索すると PDBがひっかかりましたw)
https://pubs.acs.org/action/doSearch?AllField=drugbank

あと別のデータベース案としてタンパク質とリガンドの複合体のコンフォメーションを考慮したりするのに使ったことのあるPDBbindもいいかなと思ったんですがなんかサイトが見れないですね。閉鎖したのかな？
https://en.wikipedia.org/wiki/PDBbind_database

**Comment by kzfm** [comment]
> de Novo でより薬らしい化合物を作りました、みたいな話をする時にDrugbankのデータセットと比較したりその中の化合物 (つまり薬) を再現できましたみたいな論文を見たりしますね。

ドラッグライクネスのスコアで良いような気が、、、

生成モデルでリードから薬剤まで何化合物の生成でたどり着けるかとかできれば面白そうと思ったけど、リードは流石に収載されてないしなぁ、、、

RDKitと絡める何かがあれば載せるんですが

**Comment by yamasakih** [comment]
ふむふむおっしゃる通りかもしれませんね。

ZINCを追加して、DrugBankは優先度低めでいいと思います！

**Comment by kzfm** [comment]
了解しました！

**Comment by bonohu** [comment]
生命科学分野のDBカタログ（全体で1,700件ほど）には、[77件登録](http://integbio.jp/dbcatalog/dbsearch?cck=database_catalog&order_ja=1&dbcat_search_all=&tag2=|化学物質|&tag3=&inst_country=&inst_country_others=&dbarchive=&data_downloadable=&togotv=&biosharing=&record_creation=&status=&dbcat_ministry=&taxonomy=&search=database_catalog_search&task=search)されてますが、やはりメジャーどころしか使われないですかねえ。

[日化辞](https://dbarchive.biosciencedbc.jp/jp/nikkaji/desc.html)とかはJSTがやっていて、RDF化やオープン化を進めていますが、まだまだ実用には遠いですかね。

**Comment by bonohu** [comment]
生命科学分野のDBカタログ（全体で1,700件ほど）には、[77件登録](http://integbio.jp/dbcatalog/dbsearch?cck=database_catalog&order_ja=1&dbcat_search_all=&tag2=|化学物質|&tag3=&inst_country=&inst_country_others=&dbarchive=&data_downloadable=&togotv=&biosharing=&record_creation=&status=&dbcat_ministry=&taxonomy=&search=database_catalog_search&task=search)されてますが、やはりメジャーどころしか使われないですかねえ。

[日化辞](https://dbarchive.biosciencedbc.jp/jp/nikkaji/desc.html)とかはJSTがやっていて、RDF化やオープン化を進めていますが、まだまだ実用には遠いですかね。

**Comment by bonohu** [comment]
手前味噌ですが、統合TV

- 「PubChemを利用して化学物質やアッセイの結果を調べる 2017」https://doi.org/10.7875/togotv.2017.121
- 「ChEMBLを使って医薬品候補となる化合物について調べる」https://doi.org/10.7875/togotv.2014.014 

などを紹介していただけると良いのではないかと思います。

ChEMBLの方は少々古くなっているようなので、統合TV作成updateチケット切っておきます。

**Comment by kzfm** [comment]
ありがとうございます。追加しました。
