### ISSUE TITLE
誤植・注釈など

### ISSUE THREAD

**Issue by kokitsuyuzaki** [Mishima-syk/py4chemoinformatics#40]
みなさま、執筆お疲れ様です。
先日のMishima.sykではお世話になりました。
ケモインフォは素人ですが、非常に読みやすく、一気に読み通せました。
幾つか気になった点があったので、フィードバックしてみます。

# 誤植
- page 29 : SMIRKS → SMILES
- page 31 : つかて → 使って
- page 37 : 覚えてしまうと よいです → 覚えてしまうとよいです（半角スペースが他にも入っているかもしれません）
- page 40 : ChEMB → ChEMBL
- page 44 : SupportVectorMachine、LogisticRegiression、ArtificialNeuralNetwork → Support Vector Machine、Logistic Regiression、Artificial Neural Network
- page 53 : UnderEstimate → Under Estimate（または、「過小評価」？）
- page 44,49 : ディープラーニグ、ディープラニング、ディプラーニング → ディープラーニング
- page 45 : Thensorflow → Tensorflow（コードのほうにもthensorflowという記述があるのですが、コレはどっちが正しいですか？）
- page 46 : Coalb → Colab
- page 51 : 用意おり → 用意されており
- page 51 : Backprobagation → Backpropagation/Back Propagation/Back-propagationなど

# 注釈が欲しい箇所
- page 30 : スキャフォールドとは
- page 42 : confusion matrixとは
- page 42 : f1スコアとは（あとF1と書いた方がいいかも？）
- page 43 : R2スコアとは
- page 43 : インピーダンスミスマッチとは
- page 49 : One-hotベクトルとは
- page 55 : 生成モデルとは（よくある識別モデルとの対比みたいな説明を入れるのはどうでしょうか）

# 表記ゆれ
- page 31 : smilesが小文字
- page 45,46,54 : Github → GitHub

# その他気になった点
- page 23 : 自分は専門外なのですが、フィンガープリントは部分構造をベクトル化させたもの、SMILESはそれを記述したファイルの種類（拡張子）、という理解であってますか？SMILESとの対応がわかりませんでした。
- page 42,43 : F1スコア、R2スコアの計算結果・値は見れないですか？AsciidocはMarkdownだから、コマンドの評価した結果は見れないですかね？
- page 44 : KerasとTensorflowでどちらがどちらを内包している関係なのかがわかりません。Kerasの中でTensorflowが動いているのか、TensorflowがKerasを動かしているのか？
- page 44 : 隠れ層が"分岐"というところがあまりイメージできませんでした。1つのシナプスが次のレイヤーの複数のシナプスにつながるところですか？深層学習では一般的に言われているフレーズでしょうか？
- page 51 : Epochsは増やしすぎると過学習するというのは知らなかったのですが、何か参考文献はありますか？
- page 53 : DNNが自動で特徴量を作るという説明（例えば画像でSIFTを使わずPrimitiveなデータ（ピクセル？）のまま古典的な機械学習手法を使うとうまくいかなかったのでしょうか？変数選択はあらゆる機械学習手法が自動でやってそうですが）

**Comment by kzfm** [comment]
フィードバックありがとうございます。検討して修正、追記します！

**Comment by kzfm** [comment]
page23.

> フィンガープリントは部分構造をベクトル化させたもの

これは合っています

> SMILESはそれを記述したファイルの種類（拡張子）、という理解であってますか？

これは違います。SMILESは化合物の表現方法の一つです。
ペプチドをSARDEEWGGと表現できるように化合物もC(=O)(=O)などと文字列で表現できます。

**Comment by kokitsuyuzaki** [comment]
なるほど、SMILESデータを何らかの方法でベクトル化させたのがフィンガープリントで、幾つか方法がありえるということですね。
