### ISSUE TITLE
DLの章で説明不足なところ

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#46]
page 44 : KerasとTensorflowでどちらがどちらを内包している関係なのかがわかりません。Kerasの中でTensorflowが動いているのか、TensorflowがKerasを動かしているのか？
page 44 : 隠れ層が"分岐"というところがあまりイメージできませんでした。1つのシナプスが次のレイヤーの複数のシナプスにつながるところですか？深層学習では一般的に言われているフレーズでしょうか？
page 51 : Epochsは増やしすぎると過学習するというのは知らなかったのですが、何か参考文献はありますか？
page 53 : DNNが自動で特徴量を作るという説明（例えば画像でSIFTを使わずPrimitiveなデータ（ピクセル？）のまま古典的な機械学習手法を使うとうまくいかなかったのでしょうか？変数選択はあらゆる機械学習手法が自動でやってそうですが）

**Comment by iwatobipen** [comment]
説明を追加してみました。

**Comment by kzfm** [comment]
page 44 : KerasとTensorflowでどちらがどちらを内包している関係なのかがわかりません。Kerasの中でTensorflowが動いているのか、TensorflowがKerasを動かしているのか？

OK

**Comment by kzfm** [comment]
page 44 : 隠れ層が"分岐"というところがあまりイメージできませんでした。1つのシナプスが次のレイヤーの複数のシナプスにつながるところですか？深層学習では一般的に言われているフレーズでしょうか？

これは私もよくわからないのでとりあえずクローズするけどまたreopenされる可能性が高いと思います。

**Comment by kzfm** [comment]
Epochsを増やすとなぜ過学習のリスクがあるのか？

はなぜ？にきちんと答えてない気がするけどとりあえずクローズするけどreopenの可能性は高いです。
とくにに段落目はなぜ？と関係あるのか？
