### ISSUE TITLE
ch09 のTYPO

### ISSUE THREAD

**Issue by yamasakih** [Mishima-syk/py4chemoinformatics#52]
以下の3つをTYPOとしてあげておきます。ご検討よろしくお願いします

最初のインポートで

```
from sklearn.metrics import confusion_matrix, F1_score
```

`F1_score` ではなく `f1_score` でしょうか。

> Confusion matrixとは
Confusion matriｘはクラス分類の結果をまとめた表です。クラスを正しく分類できているかをわかりやすく視覚化できTP,TNが多くFP,FNが少ないほどよく分類できているということになります。

2行目のxが全角

> F1 scoreとは
正しいと予測されたもののうち本当に正しいものの割合を適合率と呼ぶ precision=TP/(TP+FP)
正しいものが正しいと予測された割合を再現率と呼ぶ recall=TP/(TP+FN)
F1スコアは適合率と再現率の調和平均となり
F1 = 2 * (precision * recall) / (precision + recall)
で計算されます。

`F1 score`, `F1スコア` と文字の揺らぎがある

**Comment by kzfm** [comment]
修正しました
