### ISSUE TITLE
ch05 ヘテロシャッフリング

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#62]
二番目の例はスキャフォールドを超えてシャッフリングしていて気持ち悪くないですか？

スキャフォールドを指定するオプションはコードが複雑になるなら、エクスキューズ入れておいたほうが良いような気がします。

参考文献の補足文章は私の方で追加しておきます。

**Comment by iwatobipen** [comment]
了解です
