### ISSUE TITLE
ch05 typo

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#67]
RDKIT -> RDKit

それから変換後１変換後２ではなく説明を入れたほうがよいです。

「66の芳香環」もケミスト以外には理解できないですね

**Comment by iwatobipen** [comment]
説明を追記しましたがヘテロシャッフル部分のコードを改良しようと思うのでそれが終わった段階で文章も修正する可能性があります。

**Comment by kzfm** [comment]
了解です

**Comment by kzfm** [comment]
、オキサゾールと呼ばれる5員環構
造を有しております->有しています
