### ISSUE TITLE
ch11 コメントされたコードの必要性の有無

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#69]
# DNN用のライブラリを読み込みます。 tensorflowに統合されたKeras
を使うように変えました(20190306)

っていうコメントされたコードは必要ですか？

**Comment by iwatobipen** [comment]
ありがとうございます。PDF側のコードと差異が発生していたため書いていました。
今のバージョンではそれはないのでコメント部分を削除しました。
