### ISSUE TITLE
ch 05 SDFの説明

### ISSUE THREAD

**Issue by yamasakih** [Mishima-syk/py4chemoinformatics#74]
>複数の化合物を一つのファイルに格納する方法にはいくつかありますが、sdfというファイル形式を利用するのが一般的です。
> sdfフォーマットとは？
> MDL社で開発された分子表現のためのフォーマットにMOL形式というものがあります。このMOL形式を拡張したものがSDF形式です。具体的にはMOL形式で表現されたものを""という行で区切ることにより、複数の分子を取り扱えるようにしてあります。

`""` ではなく `$$$$` ではないでしょうか？

あと`sdfというファイル形式`と書いてて次の行で`sdfフォーマットとは？`となっており、  
その後、`フォーマットにMOL形式`というものがありと書いています。  

最初の説明だと`形式=フォーマット`と考えそうだけど、次の説明だと`フォーマットのサブクラス(あるいは部分集合)に形式が含まれる`と感じる文章かなと思いました。

こちらは気になるけど気持ちもわからなくないという感じの1点なので  
皆様が問題ないと思えばそのままでいいと思います。

ご検討よろしくお願いします。

**Comment by iwatobipen** [comment]
対応します

**Comment by yamasakih** [comment]
ご対応ありがとうございます！ 👏 

`sdというファイル形式` というように書くなら少し後ろの

```
sdファイルをChEMBLからダウンロードする
4章を参考にChEMBLのトポイソメラーゼII阻害試験(CHEMBL669726)の構造データをsdfファイル形式でダウンロードします。
```

こちらも `sdファイル形式` と統一した方が良いかなと思いました。  
いかがでしょうか？

**Comment by yamasakih** [comment]
@iwatobipen
