### ISSUE TITLE
環境設定周りについて

### ISSUE THREAD

**Issue by dichika** [Mishima-syk/py4chemoinformatics#83]
こちらの資料でケモインフォを勉強させていただいています。
大変わかりやすい資料をありがとうございます。
当方、Macを利用しているのですが、環境周りで２点そのままでは動かない部分があったのでご報告です。

1. 仮想環境でのjupyter notebook起動について
[こちら](https://github.com/Mishima-syk/py4chemoinformatics/blob/master/ch03_python.asciidoc#jupyter-notebook%E3%81%A7%E4%BE%BF%E5%88%A9%E3%81%AB%E4%BD%BF%E3%81%8A%E3%81%86)について、仮想環境側でもjupyter notebookをインストールする必要がありました。
`(py4chemoinformatics) $ conda install notebook ipykernel`

2. 仮想環境
[こちら](https://github.com/Mishima-syk/py4chemoinformatics/blob/master/ch02_installation.asciidoc#conda%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%82%82%E3%81%86%E5%B0%91%E3%81%97%E8%A9%B3%E3%81%97%E3%81%8F)で仮想環境から出る際のコマンドとして`source deactivate`とありますが、`conda deactivate`とする必要がありました。
https://stackoverflow.com/questions/53454777/conda-source-deactivate-bash-deactivate-no-such-file-or-directory

**Comment by kzfm** [comment]
報告ありがとうございます。

1. 仮想環境側にanacondaをインストールしてもjupyterが一緒にインストールされなかったということでしょうか？

**Comment by kzfm** [comment]
2はdeprecationwarning出てますね。修正しておきます、ありがとうございました

`DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.`

**Comment by dichika** [comment]
１についてですが、[こちら](https://github.com/Mishima-syk/py4chemoinformatics/blob/master/ch02_installation.asciidoc#%E4%BB%AE%E6%83%B3%E7%92%B0%E5%A2%83%E3%81%AE%E6%A7%8B%E7%AF%89%E3%81%A8%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB)に沿ってAnacondaインストール→仮想環境構築という形で進めました。
仮想環境ではない、base環境では`(base)$ jupyter notebook`として問題なく起動できていました。

**Comment by kzfm** [comment]
了解です、注釈付けておきます。

**Comment by yamasakih** [comment]
```
$ source activate 仮想環境の名前 # 仮想環境を使う(mac/linux)
```

こちらも  

```
conda activate 仮想環境の名前
```

の方が良いかもですね。

**Comment by yamasakih** [comment]
@kzfm 

```
$ source activate 仮想環境の名前 # 仮想環境を使う(mac/linux)
```

こちらも  

```
conda activate 仮想環境の名前
```

の方が良いかもですね。
