### ISSUE TITLE
第12章

### ISSUE THREAD

**Issue by Ishidomasami** [Mishima-syk/py4chemoinformatics#85]
pen @iwatobipen  様

貴著「AI創薬のためのケモインフォマティクス入門」で学んでいる初学者です。Anaconda(python3.7)、spyderで演習してます。教えていただきたいのは第12章の下記の部分は、具体的にどのような操作で訓練するのでしょうか。
./main.py --scoring-function tanimoto --scoring-function-kwargs query_structure 'N[C@@H](CC(=O)N1CCn2c(C1)nnc2C(F)(F)F)Cc3cc(F)c(F)cc3F' --num-steps 3000 --sigma 80 

また、pytorchと相性が悪いようで、下記のimportがうまくいきません。
from model import RNN
from data_structs import Vocabulary
from utils import seq_to_smiles

ご多忙のところ、ご助言いただければ幸いです。

石堂正美＠茨城県

**Comment by kzfm** [comment]
https://twitter.com/iwatobipen/status/1160913694454194176
