### ISSUE TITLE
ch08. HDBSCAN

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/py4chemoinformatics#94]
> 今回はmin_sample=5とし、クラスタを形成時に最低限含まれるべき化合物数を5としました。このパラメータを増減すると、異なる出力が得られますので、ある程度試行錯誤してみるのも良いでしょう。 

とあるが、なんのために試行錯誤する必要があるかの説明があったほうがよいと思います。

**Comment by iwatobipen** [comment]
ご指摘ありがとうございます。説明を追加しました。
