### ISSUE TITLE
資料の修正について（ch1, ch6, ch8）

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [Mishima-syk/py4chemoinformatics#95]
はじめまして。東大の柳澤と申します。
わかりやすい資料を作成していただいており、ありがとうございます。

資料をさらっと8章まで通読した中で、気になった点が幾つかありますので、issueとして共有いたします。ページ数は Version 1.1 2019/12/28 に準拠しています。

------

- p.5 「2.x系はサポートが2020年に終了するため、新しく～～～」
  - →2020/1/1なので、「2019年に終了する（終了した）」あるいは「2020年1月1日をもって終了する（終了した）」と記載した方が間違いが無いと思いました。（あと4日ですね）
- p.30 「イナビルの分子量が約350,ALogPが-2.92だったので、ZINCの分子量350-375,LogP=-1の340万化合物～」
  - → LogPが-1以下（未満？）と明記した方が良いように思います。
- p.30「以下はjupyter notebook上でwgetコマンドでZINCのデータセットをダウンロードする例です」
  - →句点「。」を追加。
- p.30「続いてイナビル(LANIMAMIBIR)との類似度を～」
  - → LANI "N" AMI "V" IR （タイポ修正）
- p.53「一般的にはPCAやtSNEでは既存のケミカルスペースに新しい化合物を投影できません。」
  - →これはtSNEについては正しいのですが、PCAについては間違っていると思います。事実、`sklearn.decomposition.PCA()` には `transform()` メソッドがあり、既に作成された主成分空間に新たな化合物を投影することが可能です。

**Comment by kzfm** [comment]
はじめまして。ご指摘ありがとうございます。

p.53はPCAにはPCRあるからおかしいだろうと思っていたので修正しておきます。

**Comment by iwatobipen** [comment]
yanagisawa-san, kzfm-san
Issueありがとうございます。PCAに関する部分修正いたしました。

**Comment by keisuke-yanagisawa** [comment]
@iwatobipen さん、早速のご対応ありがとうございました。

**Comment by kzfm** [comment]
p.30 も修正しました

**Comment by keisuke-yanagisawa** [comment]
@kzfm さんも、ありがとうございました！
またしばしば確認いたしますので、何か気付いたらissue立てたり、場合によってはpull request投げるなどさせていただきます。よろしくお願いいたします。
