### ISSUE TITLE
ch05_hetero_shuffle.ipynbのtypoについて

### ISSUE THREAD

**Issue by KYC-JTCPRI** [Mishima-syk/py4chemoinformatics#97]
昨日より勉強をさせていただいております。ヘテロシャッフリングなど創薬化学者に実際に使ってもらいたくなる実例で学習できて感謝しております。

さて
https://github.com/Mishima-syk/py4chemoinformatics.git
からダウンロードした
ch05_hetero_shuffle.ipynbの
In [6]にて

ht=HeteroSuffle(mol1, core1)
は
ht=HeteroShuffle(mol1, core1)

でないと正常動作しませんでした。
僭越ではございますが取り急ぎお知らせまで。

**Comment by KYC-JTCPRI** [comment]
In [11]
も同様でした。

**Comment by iwatobipen** [comment]
Thanks for reporting typo! Ijust fixed them. ;-)

**Comment by KYC-JTCPRI** [comment]
Thank you for your great work!
