### ISSUE TITLE
Issue regarding fingerprinting analysis for compound of our interest against multiple set of compouds

### ISSUE THREAD

**Issue by sharathbio123** [Mishima-syk/py4chemoinformatics#98]
Dear Mishima,

Hope you are doing well.

You have done an excellent job by creating py4chemoinformatics for various chemoinformatic approaches. I just wanted to know, how to do the fingerprinting analysis for multiple compounds (for instance, i have list FDA approved drugs) against compound of my interest. Any notes would be greatly appreciated.

**Comment by kzfm** [comment]
Dear  sharathbio123,

Thank you for reading our material, and do you want to perform Ligand Based Virtual Screening (LBVS)?
If so, the Virtual Screening Section will help you, EAED.smi file corresponds to FDA approved drugs.

https://github.com/joofio/py4chemoinformatics/blob/master/ch06_similarity.asciidoc#virtual-screening
https://github.com/Mishima-syk/py4chemoinformatics/blob/master/ch06_similarity.asciidoc#%E3%83%90%E3%83%BC%E3%83%81%E3%83%A3%E3%83%AB%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0

Best regards,
Kaz
